# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080
spring.application.name=api-gateway

# ===============================
# EUREKA CONFIGURATION
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ===============================
# CONFIG SERVER INTEGRATION
# ===============================
spring.config.import=optional:configserver:http://localhost:8888

# ===============================
# GATEWAY DISCOVERY ROUTING
# ===============================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true