
# ===============================
# SERVER CONFIG
# ===============================
server.port=8084

# Service Name (for Eureka & Gateway routing)
spring.application.name=cart-service


# ===============================
# DATABASE CONFIG (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/cart_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# LOGGING
# ===============================
logging.level.org.springframework=INFO
logging.level.com.ecommerce=DEBUG


# ===============================
# EUREKA CLIENT
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true



# ===============================
# JACKSON (Optional)
# ===============================
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false


# ===============================
# SWAGGER (OpenAPI)
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true